<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Laravel\Socialite\Facades\Socialite;
use Illuminate\Support\Facades\Auth;
use App\Providers\RouteServiceProvider;
use App\Models\Student;
use Illuminate\Support\Str;

class AppleLoginController extends Controller
{
    public function redirectToApple()
    {
        return Socialite::driver('sign-in-with-apple')->redirect();
    }


    public function handleAppleCallback()
    {
        $user = Socialite::driver('sign-in-with-apple')->user();

        $existingUser = Student::where('apple_id', $user->id)->first();

        if ($existingUser) {
            // Log in the existing user.
            auth()->login($existingUser, true);
        } else {
            // Create a new user.
            $newUser = new Student();
            $newUser->first_name = $user->name;
            $newUser->last_name = $user->name;
            $newUser->email = $user->email;
            $newUser->facebook_id = $user->id;
            $newUser->password = bcrypt(request(Str::random())); // Set some random password
            $newUser->save();

            // Log in the new user.
            auth()->login($newUser, true);
        }

        // Redirect to url as requested by user, if empty use /dashboard page as generated by Jetstream
        return redirect()->intended('/');
    }
}